export const GET_MEETINGS = "GET_MEETINGS";
export const ADD_MEETING = "ADD_MEETING";
export const UPDATE_MEETING = "UPDATE_MEETING";
export const GETSINGLE_MEETING = "GETSINGLE_MEETING";
export const DELETE_MEETING = "DELETE_MEETING";
